language: node_js

node_js:
  - 'node'
  - '10'
  - '8'
  - '6.9'
  - '4.4'
  - '0.12'

script:
  # run tests with the version of node from the matrix
  - npm test

addons:
  code_climate:
    repo_token: 08120a5f6442a389a93094fd9f5f25099e912f4807936ff46f85234037ca9585

after_script:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info

jobs:
  include:
    - stage: lint
      node_js: '6.9'
      script: npm run lint
      after_script: skip
    - stage: npm release
      if: tag IS present
      node_js: '6.9'
      script: echo "Deploying to npm ..."
      after_script: skip
      deploy:
        provider: npm
        email: vatev.1+npm@gmail.com
        api_key:
          secure: EIPTcJqm8I8dB1vrL1/mlDxjjOVXlT9cU3tIkF0rDf556FOate6jvjlGlqJFpOek1CrFcxbUD47BdILdZzX0zhzc2M5zYqJGRMGtEi0JlDr92dYLdIwS/peYZ34svFzbFQpR6ke45n55YYuVkC2HD5DabAMzogNlI67NmvKdedAUWVOSRZfV8kCtIM+G2UpLTwKPvE6okyuyM51XazqyyZLnnL5Q8MS2lzTycLIQm7Xvgkc8Q8w4PLkDL3D6if1KXz2teKeIf6MMHa79jnyv97MGdX8REFH4sGvqYDKx5rnlQpyqVrt1gnIJ47at2rX98JNsr27ayq/LJ7QTzFd4T/QRXkeTvIeM0kLeofbDjtHwRII0newF6GkBSwc4L9ZLfeoECuwwvekprBTAcsXlX2dhbFFCmAkLZSfgmoDPx6LxQnNawFExBBtZ/GMhbQHOHaBE4Q+RBbrUh3T35D8Oqhqb9cjFmSzJIT497cMzMr9cko6VCkpNuSWPjMee8Oxac1M1a5A6nNUC5MWF76uSYjhtU/gqIN9/61L9Uv3ukeZLdX69UAzh4ELN3U6gCdutWH0gFqRhzyYPpCnS8TnZ0Pcot2qpCfSdLNyfdSM1gIb5pBFnp/TxVIZsd8QNxHph3ENIAZJCgmPYp32BpOuM3MxEB6hy9ZV/VmizYfs/4M0=
        on:
          tags: true
          repo: catdad/grandma
