language: node_js

node_js:
  - 'node'
  - '7.2'
  - '6.9'
  - '5.10'
  - '4.4'
  - 'iojs'
  - '0.12'

script:
  - npm test
  - npm run lint

addons:
  code_climate:
    repo_token: 08120a5f6442a389a93094fd9f5f25099e912f4807936ff46f85234037ca9585

after_script:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
